### ISSUE TITLE
Sorting code removed from France address format

### ISSUE THREAD

**Issue by F21** [google/libaddressinput#177]
I noticed that the sorting code `%X` was removed during an update to the address metadata at `https://chromium-i18n.appspot.com/ssl-address/data/FR`.

Previously, the address format was `%O%n%N%n%A%n%Z %C %X`, but the data update changed it to `%O%n%N%n%A%n%Z %C`. From my understanding, the sort code is substituted with `CEDEX` for recipients of large-volume mail.

See:
- https://en.wikipedia.org/wiki/Postal_codes_in_France#CEDEX
- http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/fraEn.pdf

Should the sorting code `%X` parameter be reinstated in the address format?

**Comment by panigrc** [comment]
Other definitions were changed too.
For example in POLAND/PL and ROMANIA/RO the 'S' (Administrative area such as a state, province, island etc) requirement was also removed.

**Comment by bojanz** [comment]
I also noticed two potentially odd changes:
- The sorting code removal (France was the only one that used it, the field would now always be unused)
- The locality removal from Japan (which now only has the address lines 1/2 and the administrative area)

Would love to get clarification before I pull these changes into the PHP library.

**Comment by lararennie** [comment]
The French and Japanese changes seem odd to me too.

**Comment by sockix** [comment]
w/r/t France: The request to remove it from France was made by a client who was receiving bug reports that there shouldn't be an explicit CEDEX field in France and that no other shipping type forms ever included it. The guidance we received seemed to indicate that it was reasonable to remove it. 
Personally I'm not too familiar with addressing conventions in France, so if you strongly feel that this decision should be revisited, then LMK [65538395].

w/r/t Japan: Other than the address line field, each of the other fields are intended to only have a single value.  In short, there seemed to be confusion about what value to enter into the 'locality' field given that there are several possible candidates (ie. city, ward, town, village, district).  Following some discussion and research, since it seemed that in Japan it was most common to have a single textbox for the entire address, so we removed the separate locality field in order to help eliminate confusion [63338657].

**Comment by lararennie** [comment]
When we last looked at CEDEX, the problem was the UI: it seemed to be best supported as a tick-box, where if you said yes, there was an optional number that you could add. However, no one ever implemented this (only relevant for some addresses in France). The other way to support it is to add it to the locality field, but this makes anything where you want to group addresses by locality a bit messier, you'd have to strip this bit first. (I can imagine no one else ever has it on a shipping type form, because most shipping forms are US-centric.)

I feel like there was an open-source bug issue about this already somewhere?

w.r.t Japan: For every country, for every user, the easiest thing is just to enter your address in a single box; the point of a semi-structured widget is to be able to ensure the address is reasonable when we don't have geocoding support behind to try and work out what the user meant, or when geocoding is wrong, and also to help people converting from one format to another etc.

On the other hand, I know it was very confusing to users to know what to put there, so I have sympathy for removing it altogether. The problem is that a city-like-thing *is* required, and now you can't specify that....

**Comment by mimckenna** [comment]
Our experience with CEDEX - we've only recently added a field to be able to collect CEDEX, but we really don't have any live data with it yet.  Users have just added it to their city field, if needed.  But ... our new address schema includes a field where CEDEX would go, and is set up so when we normalize addresses, any values after the city will go into CEDEX.

Last time I looked, a year ago, the `%X` field is used in only France and French territories BF, BL, CI, FR, GF, GP, JM, MC, MF, MQ, MW, NC, PM, RE, WF, YT - except maybe Burkina Faso.

And for Japan, we recently made the city field optional for validating against our [address schema](https://github.com/paypal/api-standards/blob/master/v1/schema/json/README_address.md).  For us it is the second-level administrative level `admin_area_2` field that matches HTML51 `address-level2` autocomplete field, or *libaddressinput* `city` field.  The problem was that for users in "Tokyo", the prefecture is "Tokyo", which also happens to be their city.  Users would get confused after entering their prefecture with a pull-down of enums, and not want to enter the value twice.  Then, some of our UI's have started auto-completion of the address data using the Google Places API, and we would get valid addresses with the locality field empty.  So we kept it, since it's already in our data, and thousands of accounts have "city" filled in that we still need to format correctly.
But city is optional now.
