### ISSUE TITLE
Irish counties

### ISSUE THREAD

**Issue by snpower** [google/libaddressinput#185]
The county list for Ireland is a list like Co. Galway, Co. Cork, etc.

However, for Dublin it just has Co. Dublin. While that is technically right (if you just want a list of the counties of Ireland), it doesn't work for billing or shipping addresses, where we have Dublin 1, Dublin 2 and so on, as well as Co. Dublin for those who live outside the city. The post office expects this information in the addresses, and when using this library to build ecommerce checkout solutions, this is not very helpful.

FYI if you look up the address for the eircode (aka postal code) for the head post office in Ireland, then you will see it returns Dublin 1 in the address and not Co. Dublin https://correctaddress.anpost.ie and https://finder.eircode.ie/#/ (eircode D01 F5P2)

Similarly when searching Google's address in Dublin with eircode D04 V4X7, it returns Dublin 4, not Co. Dublin.

As a side issue, by including the unneeded "Co. " bit in the county name, it is not easy to jump to the county you want in a dropdown by typing a letter.

**Comment by jeffdgr8** [comment]
Something else I experienced with Ireland addresses is that Google's reverse geocoding API returns admin areas in the format "County Limerick", which fails to validate against Google's address validation metadata list, which abbreviates county as "Co. Limerick".

**Comment by sockix** [comment]
Things such as 'Dublin 4' are considered postal districts, which are actually sub-localities (smaller than even the city of Dublin). See for example the history of 'Dublin 4' on [wikipedia](https://en.wikipedia.org/wiki/Dublin_4).  

This is tricky because as you mention, the dropdown is for the county which does appear to be a required field. It appears that the locality field might be the most appropriate place for these postal districts when filling out the form for an address in Dublin.  

As for the other point about not being jump down to the county easily, I personally agree.  Removing the 'Co.' prefix from display in the widgets seems reasonable, and something that I'm looking into.   

Jeff, with regards to the 'Co.' prefix issue, it does appear that the reverse geocoding bug has been fixed since you originally posted this issue.  Apologies for not updating these issue quicker.
